### ISSUE TITLE
No module named vs

### ISSUE THREAD

**Issue by NileshKute** [spillai/pybot#2]
Hello,

I will try to use pybot, But I facing below mention errors.
can you give me solution/suggestion for this.  

Traceback (most recent call last):
  File "test_rosbag.py", line 17, in <module>
    from pybot.externals.lcm.draw_utils import publish_pose_list, publish_cloud
  File "/opt/anaconda2/lib/python2.7/site-packages/pybot-0.1-py2.7.egg/pybot/externals/lcm/draw_utils.py", line 16, in <module>
ImportError: No module named vs

Thanks,
Nilesh.

**Comment by spillai** [comment]
Unfortunately the modules within externals.lcm aren't fully supported yet (since it depends on a few other libraries). Can you comment out the publish_pose, and publish_cloud lines, including the import line, and see if you get any other issues? I'll get to fixing all of this very soon.

**Comment by NileshKute** [comment]
Hello,
I comment to all modules which you mentioned.
Then I tried to execute test_rosbag.py script. Script run, but gave below mention log.

~/Desktop/tests$ python test_rosbag.py -f ./2017-07-03-17-36-05.bag
ROSBagReader :: OFFLINE mode
ROSBagReader :: Loading ROSBag ./2017-07-03-17-36-05.bag ...
ROSBagReader :: Done loading ./2017-07-03-17-36-05.bag in  0.17 seconds
------------------------------------------------------------------------------------------------------------------------
path:        ./2017-07-03-17-36-05.bag
version:     2.0
duration:    2:13s (133s)
start:       Jul 03 2017 17:36:06.01 (1499083566.01)
end:         Jul 03 2017 17:38:19.80 (1499083699.80)
size:        3.8 GB
messages:    3775
compression: none [3775/3775 chunks]
types:       sensor_msgs/Image [060021388200f6f0f447d0fcd9c64743]
topics:      camera/depth_registered/sw_registered/image_rect   2012 msgs @ 29.6 Hz : sensor_msgs/Image
             camera/rgb/image_color                             1763 msgs @ 29.8 Hz : sensor_msgs/Image
------------------------------------------------------------------------------------------------------------------------
ROSBagReader :: Reading ROSBag from 0.00% onwards
Traceback (most recent call last):
  File "test_rosbag.py", line 59, in <module>
    print('Read {} frames'.format(idx+1))
NameError: name 'idx' is not defined

Not going to loop.
What I did wrong?
Can you tell me?

Thanks,
Nilesh
